spring.application.name=kafka.connect.manager
server.port=8888
kafka.connect.url=http://localhost:8083

# Kafka Streams Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.streams.application-id=order-deduplication-app

# Topic Configuration
kafka.streams.topics.orders.source=orders-topic
kafka.streams.topics.orders.cleaned=orders-cleaned-final

# Disable Spring's auto-configuration for Kafka Streams
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration

spring.task.scheduling.enabled=true

# CSV Processing Paths
csv.watch.directory=/home/hussain/CodeBase/ps-sql/kafka/data/upload
csv.input.directory=/home/hussain/CodeBase/ps-sql/kafka/data/input

# Kafka Connect Paths
kafka.connect.input.path=/tmp/input
kafka.connect.finished.path=/tmp/finished
kafka.connect.error.path=/tmp/error

# Connector configs save path
connector.configs.save.path=src/main/resources/connector-configs

# Connector Cleanup on Startup
connector.cleanup.on.startup=true
connector.cleanup.skip.patterns=.*-internal$,.*-system$,connect-.*
connector.cleanup.delay.ms=500