spring.application.name=kafka.connect.manager

server.port=8888

kafka.connect.url=http://localhost:8083

# Kafka Streams Configuration
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.streams.application-id=order-deduplication-app

# Topic Configuration
kafka.streams.topics.orders.source=orders-topic
kafka.streams.topics.orders.cleaned=orders-cleaned-final

# Disable Spring's auto-configuration for Kafka Streams
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.kafka.KafkaAutoConfiguration
